import { MovementType } from "../units/Movement";
import { DamageType } from "../units/Damage";
import { AIType } from "../units/AIType";
import type { UnitConfig } from "../units/UnitConfig";

// Base icon path root
const ICON_BASE = "/assets/icons/unit_icons";

export const Characters = {
  // ==========================================
  // 1. TANK DIVISION
  // ==========================================
  CYCLOPS: {
    name: "Cyclops",
    stats: {
      maxHealth: 450,
      healthRegeneration: 10,
      armor: 60,
      magicResistance: 30,
      maxShield: 0,
      meleeAttack: {
        range: 18,
        damage: 20,
        attackSpeed: 1,
        damageType: DamageType.PHYSICAL,
      },
      speed: 50,
      width: 60,
      height: 60,
      mass: 5,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.TANK,
    icon: `${ICON_BASE}/tank/cyclops.png`,
  },
  BEHEMOTH: {
    name: "Behemoth",
    stats: {
      width: 72,
      height: 72,
      speed: 50,
      mass: 6,
      maxHealth: 500,
      healthRegeneration: 5,
      meleeAttack: {
        range: 18,
        damage: 25,
        attackSpeed: 1,
        damageType: DamageType.PHYSICAL,
      },
      armor: 40,
      magicResistance: 40,
      maxShield: 0,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.TANK,
    icon: `${ICON_BASE}/tank/behemoth.png`,
  },
  GOLEM: {
    name: "Golem",
    stats: {
      width: 72,
      height: 72,
      speed: 50,
      mass: 6,
      maxHealth: 550,
      healthRegeneration: 5,
      meleeAttack: {
        range: 18,
        damage: 15,
        attackSpeed: 1,
        damageType: DamageType.PHYSICAL,
      },
      armor: 30,
      magicResistance: 70,
      maxShield: 0,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.TANK,
    icon: `${ICON_BASE}/tank/golem.png`,
  },
  DREADNOUGHT: {
    name: "Dreadnought",
    stats: {
      width: 72,
      height: 72,
      speed: 50,
      mass: 6,
      maxHealth: 450,
      healthRegeneration: 5,
      meleeAttack: {
        range: 18,
        damage: 30,
        attackSpeed: 1.2,
        damageType: DamageType.PHYSICAL,
      },
      armor: 70,
      magicResistance: 30,
      maxShield: 0,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.TANK,
    icon: `${ICON_BASE}/tank/dreadnought.png`,
  },
  LEGIONNAIRE: {
    name: "Legionnaire",
    stats: {
      width: 52,
      height: 52,
      speed: 75,
      mass: 4,
      maxHealth: 350,
      healthRegeneration: 15,
      meleeAttack: {
        range: 18,
        damage: 15,
        attackSpeed: 1.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 50,
      magicResistance: 30,
      maxShield: 0,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.TANK,
    icon: `${ICON_BASE}/tank/legionnaire.png`,
  },
  HYDRA: {
    name: "Hydra",
    stats: {
      width: 72,
      height: 72,
      speed: 50,
      mass: 6,
      maxHealth: 450,
      healthRegeneration: 20,
      meleeAttack: {
        range: 18,
        damage: 20,
        attackSpeed: 1.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 30,
      magicResistance: 30,
      maxShield: 0,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.TANK,
    icon: `${ICON_BASE}/tank/hydra.png`,
  },
  YETI: {
    name: "Yeti",
    stats: {
      width: 60,
      height: 60,
      speed: 75,
      mass: 5,
      maxHealth: 400,
      healthRegeneration: 10,
      meleeAttack: {
        range: 18,
        damage: 20,
        attackSpeed: 1,
        damageType: DamageType.PHYSICAL,
      },
      armor: 40,
      magicResistance: 40,
      maxShield: 0,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.TANK,
    icon: `${ICON_BASE}/tank/yeti.png`,
  },

  // ==========================================
  // 2. FIGHTER & VANGUARD DIVISION
  // ==========================================
  PHOENIX: {
    name: "Phoenix",
    stats: {
      width: 52,
      height: 52,
      speed: 100,
      mass: 4,
      maxHealth: 250,
      healthRegeneration: 10,
      meleeAttack: {
        range: 16,
        damage: 35,
        attackSpeed: 2,
        damageType: DamageType.PHYSICAL,
      },
      armor: 20,
      magicResistance: 40,
      lifeSteal: 20,
      maxShield: 0,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.FIGHTER,
    icon: `${ICON_BASE}/fighter/phoenix.png`,
  },
  WEREWOLF: {
    name: "Werewolf",
    stats: {
      width: 52,
      height: 52,
      speed: 100,
      mass: 4,
      maxHealth: 300,
      healthRegeneration: 5,
      meleeAttack: {
        range: 16,
        damage: 40,
        attackSpeed: 2.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 20,
      magicResistance: 20,
      maxShield: 0,
      lifeSteal: 30,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.FIGHTER,
    icon: `${ICON_BASE}/fighter/werewolf.png`,
  },
  TEMPLAR: {
    name: "Templar",
    stats: {
      width: 52,
      height: 52,
      speed: 75,
      mass: 4,
      maxHealth: 350,
      healthRegeneration: 5,
      meleeAttack: {
        range: 16,
        damage: 35,
        attackSpeed: 1.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 35,
      magicResistance: 35,
      lifeSteal: 10,
      maxShield: 0,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.FIGHTER,
    icon: `${ICON_BASE}/fighter/templar.png`,
  },
  GLADIATOR: {
    name: "Gladiator",
    stats: {
      width: 52,
      height: 52,
      speed: 100,
      mass: 4,
      maxHealth: 300,
      healthRegeneration: 5,
      meleeAttack: {
        range: 16,
        damage: 45,
        attackSpeed: 2,
        damageType: DamageType.PHYSICAL,
      },
      armor: 30,
      magicResistance: 20,
      maxShield: 0,
      lifeSteal: 15,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.FIGHTER,
    icon: `${ICON_BASE}/fighter/gladiator.png`,
  },
  SPARTAN: {
    name: "Spartan",
    stats: {
      width: 52,
      height: 52,
      speed: 75,
      mass: 4,
      maxHealth: 300,
      healthRegeneration: 5,
      meleeAttack: {
        range: 16,
        damage: 40,
        attackSpeed: 2,
        damageType: DamageType.PHYSICAL,
      },
      armor: 40,
      magicResistance: 20,
      maxShield: 0,
      lifeSteal: 10,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.FIGHTER,
    icon: `${ICON_BASE}/fighter/spartan.png`,
  },
  SAMURAI: {
    name: "Samurai",
    stats: {
      width: 52,
      height: 52,
      speed: 100,
      mass: 4,
      maxHealth: 250,
      healthRegeneration: 5,
      meleeAttack: {
        range: 16,
        damage: 50,
        attackSpeed: 3,
        damageType: DamageType.PHYSICAL,
      },
      armor: 25,
      magicResistance: 25,
      maxShield: 0,
      lifeSteal: 15,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.FIGHTER,
    icon: `${ICON_BASE}/fighter/samurai.png`,
  },
  VIKING: {
    name: "Viking",
    stats: {
      width: 52,
      height: 52,
      speed: 75,
      mass: 4,
      maxHealth: 350,
      healthRegeneration: 5,
      meleeAttack: {
        range: 16,
        damage: 40,
        attackSpeed: 2,
        damageType: DamageType.PHYSICAL,
      },
      armor: 30,
      magicResistance: 30,
      maxShield: 0,
      lifeSteal: 15,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.FIGHTER,
    icon: `${ICON_BASE}/fighter/viking.png`,
  },
  KNIGHT: {
    name: "Knight",
    stats: {
      width: 52,
      height: 52,
      speed: 75,
      mass: 4,
      maxHealth: 350,
      healthRegeneration: 5,
      meleeAttack: {
        range: 16,
        damage: 35,
        attackSpeed: 1.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 50,
      magicResistance: 20,
      maxShield: 0,
      lifeSteal: 10,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.FIGHTER,
    icon: `${ICON_BASE}/fighter/knight.png`,
  },

  // ==========================================
  // 3. ASSASSIN & SKIRMISHER DIVISION
  // ==========================================
  GOBLIN: {
    name: "Goblin",
    stats: {
      width: 40,
      height: 40,
      speed: 125,
      mass: 2,
      maxHealth: 150,
      meleeAttack: {
        range: 14,
        damage: 40,
        attackSpeed: 3.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 10,
      magicResistance: 10,
      maxShield: 20,
      lifeSteal: 20,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.ASSASSIN,
    icon: `${ICON_BASE}/assassin/goblin.png`,
  },
  VAMPIRE: {
    name: "Vampire",
    stats: {
      width: 44,
      height: 44,
      speed: 125,
      mass: 3,
      maxHealth: 200,
      meleeAttack: {
        range: 14,
        damage: 45,
        attackSpeed: 3,
        damageType: DamageType.PHYSICAL,
      },
      armor: 10,
      magicResistance: 10,
      maxShield: 10,
      lifeSteal: 40,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.ASSASSIN,
    icon: `${ICON_BASE}/assassin/vampire.png`,
  },
  NINJA: {
    name: "Ninja",
    stats: {
      width: 44,
      height: 44,
      speed: 150,
      mass: 3,
      maxHealth: 150,
      meleeAttack: {
        range: 14,
        damage: 55,
        attackSpeed: 3.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 15,
      magicResistance: 15,
      maxShield: 30,
      lifeSteal: 10,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.ASSASSIN,
    icon: `${ICON_BASE}/assassin/ninja.png`,
  },
  CLOWN: {
    name: "Clown",
    stats: {
      width: 44,
      height: 44,
      speed: 125,
      mass: 3,
      maxHealth: 200,
      meleeAttack: {
        range: 14,
        damage: 40,
        attackSpeed: 4,
        damageType: DamageType.PHYSICAL,
      },
      armor: 10,
      magicResistance: 10,
      maxShield: 10,
      lifeSteal: 15,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.ASSASSIN,
    icon: `${ICON_BASE}/assassin/clown.png`,
  },
  COMMANDO: {
    name: "Commando",
    stats: {
      width: 52,
      height: 52,
      speed: 100,
      mass: 4,
      maxHealth: 250,
      meleeAttack: {
        range: 14,
        damage: 60,
        attackSpeed: 3,
        damageType: DamageType.PHYSICAL,
      },
      armor: 15,
      magicResistance: 15,
      maxShield: 20,
      lifeSteal: 10,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.ASSASSIN,
    icon: `${ICON_BASE}/assassin/commando.png`,
  },
  HACKER: {
    name: "Hacker",
    stats: {
      width: 40,
      height: 40,
      speed: 125,
      mass: 2,
      maxHealth: 150,
      meleeAttack: {
        range: 14,
        damage: 50,
        attackSpeed: 3,
        damageType: DamageType.PHYSICAL,
      },
      armor: 10,
      magicResistance: 30,
      maxShield: 20,
      lifeSteal: 15,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.ASSASSIN,
    icon: `${ICON_BASE}/assassin/hacker.png`,
  },

  // ==========================================
  // 4. MARKSMAN & RANGE DIVISION
  // ==========================================
  ELF: {
    name: "Elf",
    stats: {
      width: 32,
      height: 32,
      speed: 125,
      mass: 1,
      maxHealth: 100,
      rangedAttack: {
        range: 130,
        projectileBehavior: "straight",
        damage: 35,
        attackSpeed: 4,
        projectileSpeed: 320,
        damageType: DamageType.PHYSICAL,
      },
      armor: 10,
      magicResistance: 10,
      maxShield: 0,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/marksmen/elf.png`,
  },
  SNIPER: {
    name: "Sniper",
    stats: {
      width: 40,
      height: 40,
      speed: 100,
      mass: 2,
      maxHealth: 100,
      rangedAttack: {
        range: 180,
        projectileBehavior: "straight",
        damage: 100,
        attackSpeed: 1,
        projectileSpeed: 520,
        damageType: DamageType.PHYSICAL,
      },
      armor: 10,
      magicResistance: 10,
      maxShield: 0,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/marksmen/sniper.png`,
  },
  GRENADIER: {
    name: "Grenadier",
    stats: {
      width: 44,
      height: 44,
      speed: 100,
      mass: 3,
      maxHealth: 150,
      rangedAttack: {
        range: 120,
        projectileBehavior: "straight",
        damage: 80,
        attackSpeed: 1.5,
        projectileSpeed: 260,
        damageType: DamageType.PHYSICAL,
      },
      armor: 15,
      magicResistance: 10,
      maxShield: 0,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/marksmen/grenadier.png`,
  },
  MUSKETEER: {
    name: "Musketeer",
    stats: {
      width: 44,
      height: 44,
      speed: 125,
      mass: 3,
      maxHealth: 150,
      rangedAttack: {
        range: 140,
        projectileBehavior: "straight",
        damage: 60,
        attackSpeed: 4,
        projectileSpeed: 430,
        damageType: DamageType.PHYSICAL,
      },
      armor: 10,
      magicResistance: 10,
      maxShield: 0,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/marksmen/musketeer.png`,
  },
  DRONE: {
    name: "Drone",
    stats: {
      width: 32,
      height: 32,
      speed: 150,
      mass: 1,
      maxHealth: 100,
      rangedAttack: {
        range: 125,
        projectileBehavior: "straight",
        damage: 40,
        attackSpeed: 5,
        projectileSpeed: 460,
        damageType: DamageType.PHYSICAL,
      },
      armor: 15,
      magicResistance: 20,
      maxShield: 0,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/marksmen/drone.png`,
  },
  LANCER: {
    name: "Lancer",
    stats: {
      width: 44,
      height: 44,
      speed: 100,
      mass: 3,
      maxHealth: 200,
      rangedAttack: {
        range: 100,
        projectileBehavior: "straight",
        damage: 70,
        attackSpeed: 3,
        projectileSpeed: 360,
        damageType: DamageType.PHYSICAL,
      },
      armor: 20,
      magicResistance: 10,
      maxShield: 0,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/marksmen/lancer.png`,
  },

  // ==========================================
  // 5. MAGE & CASTER DIVISION
  // ==========================================
  DRAGON: {
    name: "Dragon",
    stats: {
      width: 60,
      height: 60,
      speed: 100,
      mass: 5,
      maxHealth: 250,
      rangedAttack: {
        range: 130,
        projectileBehavior: "homing",
        damage: 60,
        attackSpeed: 2,
        projectileSpeed: 250,
        damageType: DamageType.MAGIC,
      },
      armor: 20,
      magicResistance: 40,
      maxShield: 0,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/mage/dragon.png`,
  },
  DRAKE: {
    name: "Drake",
    stats: {
      width: 52,
      height: 52,
      speed: 100,
      mass: 4,
      maxHealth: 200,
      rangedAttack: {
        range: 120,
        projectileBehavior: "homing",
        damage: 50,
        attackSpeed: 2.5,
        projectileSpeed: 270,
        damageType: DamageType.MAGIC,
      },
      armor: 15,
      magicResistance: 30,
      maxShield: 40,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/mage/drake.png`,
  },
  LICH: {
    name: "Lich",
    stats: {
      width: 44,
      height: 44,
      speed: 100,
      mass: 3,
      maxHealth: 200,
      healthRegeneration: 0,
      rangedAttack: {
        range: 140,
        projectileBehavior: "homing",
        damage: 60,
        attackSpeed: 2,
        projectileSpeed: 240,
        damageType: DamageType.MAGIC,
      },
      armor: 10,
      magicResistance: 40,
      maxShield: 20,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/mage/lich.png`,
  },
  WITCH: {
    name: "Witch",
    stats: {
      width: 44,
      height: 44,
      speed: 100,
      mass: 3,
      maxHealth: 150,
      healthRegeneration: 0,
      rangedAttack: {
        range: 130,
        projectileBehavior: "homing",
        damage: 50,
        attackSpeed: 2,
        projectileSpeed: 250,
        damageType: DamageType.MAGIC,
      },
      armor: 10,
      magicResistance: 50,
      maxShield: 40,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/mage/witch.png`,
  },
  WIZARD: {
    name: "Wizard",
    stats: {
      width: 44,
      height: 44,
      speed: 75,
      mass: 3,
      maxHealth: 200,
      healthRegeneration: 0,
      rangedAttack: {
        range: 160,
        projectileBehavior: "homing",
        damage: 70,
        attackSpeed: 1.5,
        projectileSpeed: 290,
        damageType: DamageType.MAGIC,
      },
      armor: 10,
      magicResistance: 50,
      maxShield: 50,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/mage/wizard.png`,
  },
  PYROMANCER: {
    name: "Pyromancer",
    stats: {
      width: 44,
      height: 44,
      speed: 75,
      mass: 3,
      maxHealth: 150,
      healthRegeneration: 0,
      rangedAttack: {
        range: 125,
        projectileBehavior: "homing",
        damage: 80,
        attackSpeed: 2,
        projectileSpeed: 260,
        damageType: DamageType.MAGIC,
      },
      armor: 15,
      magicResistance: 30,
      maxShield: 20,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/mage/pyromancer.png`,
  },
  BANSHEE: {
    name: "Banshee",
    stats: {
      width: 44,
      height: 44,
      speed: 125,
      mass: 3,
      maxHealth: 150,
      healthRegeneration: 0,
      rangedAttack: {
        range: 150,
        projectileBehavior: "homing",
        damage: 40,
        attackSpeed: 3,
        projectileSpeed: 310,
        damageType: DamageType.MAGIC,
      },
      armor: 10,
      magicResistance: 60,
      maxShield: 30,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.MARKSMAN,
    icon: `${ICON_BASE}/mage/banshee.png`,
  },

  // ==========================================
  // 6. SUPPORT & UTILITY DIVISION
  // ==========================================
  NECROMANCER: {
    name: "Necromancer",
    stats: {
      width: 44,
      height: 44,
      speed: 100,
      mass: 3,
      maxHealth: 250,
      healthRegeneration: 10,
      meleeAttack: {
        range: 13,
        damage: 20,
        attackSpeed: 2,
        damageType: DamageType.PHYSICAL,
      },
      armor: 20,
      magicResistance: 40,
      maxShield: 40,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.SUPPORT,
    icon: `${ICON_BASE}/support/necromancer.png`,
  },
  ALCHEMIST: {
    name: "Alchemist",
    stats: {
      width: 52,
      height: 52,
      speed: 125,
      mass: 4,
      maxHealth: 250,
      healthRegeneration: 15,
      meleeAttack: {
        range: 13,
        damage: 25,
        attackSpeed: 2,
        damageType: DamageType.PHYSICAL,
      },
      armor: 20,
      magicResistance: 20,
      maxShield: 60,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.SUPPORT,
    icon: `${ICON_BASE}/support/alchemist.png`,
  },
  MEDIC: {
    name: "Medic",
    stats: {
      width: 44,
      height: 44,
      speed: 125,
      mass: 3,
      maxHealth: 300,
      healthRegeneration: 20,
      meleeAttack: {
        range: 13,
        damage: 15,
        attackSpeed: 1.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 20,
      magicResistance: 20,
      maxShield: 30,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.SUPPORT,
    icon: `${ICON_BASE}/support/medic.png`,
  },
  PLAGUE_DOCTOR: {
    name: "Plague Doctor",
    stats: {
      width: 44,
      height: 44,
      speed: 100,
      mass: 3,
      maxHealth: 300,
      healthRegeneration: 15,
      meleeAttack: {
        range: 13,
        damage: 25,
        attackSpeed: 1.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 30,
      magicResistance: 30,
      maxShield: 40,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.SUPPORT,
    icon: `${ICON_BASE}/support/plague_dr.png`,
  },
  CYBORG: {
    name: "Cyborg",
    stats: {
      width: 52,
      height: 52,
      speed: 100,
      mass: 4,
      maxHealth: 350,
      healthRegeneration: 10,
      meleeAttack: {
        range: 13,
        damage: 30,
        attackSpeed: 1.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 30,
      magicResistance: 30,
      maxShield: 80,
    },
    movementType: MovementType.JITTER,
    aiType: AIType.SUPPORT,
    icon: `${ICON_BASE}/support/cyborg.png`,
  },
  KING: {
    name: "King",
    stats: {
      width: 44,
      height: 44,
      speed: 100,
      mass: 3,
      maxHealth: 400,
      healthRegeneration: 10,
      meleeAttack: {
        range: 13,
        damage: 35,
        attackSpeed: 1.5,
        damageType: DamageType.PHYSICAL,
      },
      armor: 40,
      magicResistance: 20,
      maxShield: 50,
    },
    movementType: MovementType.BOUNCE,
    aiType: AIType.SUPPORT,
    icon: `${ICON_BASE}/support/king.png`,
  },
  QUEEN: {
    name: "Queen",
    stats: {
      width: 44,
      height: 44,
      speed: 125,
      mass: 3,
      maxHealth: 300,
      healthRegeneration: 15,
      meleeAttack: {
        range: 13,
        damage: 25,
        attackSpeed: 2,
        damageType: DamageType.PHYSICAL,
      },
      armor: 20,
      magicResistance: 40,
      maxShield: 50,
    },
    movementType: MovementType.WANDER,
    aiType: AIType.SUPPORT,
    icon: `${ICON_BASE}/support/queen.png`,
  },
} satisfies Record<string, UnitConfig>;

export type CharacterId = keyof typeof Characters;

/**
 * Character groups used by the roster selector in the game menu.
 * Keeping this separate from UnitConfig means the menu can group
 * characters without adding UI-only data to the gameplay config.
 */
export const CharacterDivisions: ReadonlyArray<{
  name: string;
  characters: ReadonlyArray<CharacterId>;
}> = [
  {
    name: "Tank",
    characters: [
      "CYCLOPS",
      "BEHEMOTH",
      "GOLEM",
      "DREADNOUGHT",
      "LEGIONNAIRE",
      "HYDRA",
      "YETI",
    ],
  },
  {
    name: "Fighter & Vanguard",
    characters: [
      "PHOENIX",
      "WEREWOLF",
      "TEMPLAR",
      "GLADIATOR",
      "SPARTAN",
      "SAMURAI",
      "VIKING",
      "KNIGHT",
    ],
  },
  {
    name: "Assassin & Skirmisher",
    characters: [
      "GOBLIN",
      "VAMPIRE",
      "NINJA",
      "CLOWN",
      "COMMANDO",
      "HACKER",
    ],
  },
  {
    name: "Marksman & Range",
    characters: [
      "ELF",
      "SNIPER",
      "GRENADIER",
      "MUSKETEER",
      "DRONE",
      "LANCER",
    ],
  },
  {
    name: "Mage & Caster",
    characters: [
      "DRAGON",
      "DRAKE",
      "LICH",
      "WITCH",
      "WIZARD",
      "PYROMANCER",
      "BANSHEE",
    ],
  },
  {
    name: "Support & Utility",
    characters: [
      "NECROMANCER",
      "ALCHEMIST",
      "MEDIC",
      "PLAGUE_DOCTOR",
      "CYBORG",
      "KING",
      "QUEEN",
    ],
  },
];